services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.prod
      target: production
    container_name: bess-pro-frontend
    restart: unless-stopped
    ports:
      - "3003:80"
    environment:
      - NODE_ENV=production
    networks:
      - bess-network
    depends_on:
      - backend

  # Backend
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.prod
      target: production
    container_name: bess-pro-backend
    restart: unless-stopped
    ports:
      - "8010:8010"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - uploads:/app/uploads
      - logs:/app/logs
    networks:
      - bess-network
    depends_on:
      - mongodb
      - redis
      - mailpit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB ARM64
  mongodb:
    image: mongo:7.0
    container_name: bess-pro-mongodb
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-your-secure-password}
      MONGO_INITDB_DATABASE: bess-pro-prod
    volumes:
      - mongodb_prod_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - bess-network

  # Redis ARM64
  redis:
    image: redis:7.2-alpine
    container_name: bess-pro-redis
    platform: linux/arm64
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --requirepass ${REDIS_PASSWORD:-your-redis-password}
    volumes:
      - redis_prod_data:/data
    networks:
      - bess-network

  # Python Energy Calculation Service (PVLIB + BESS)
  energy-calculation-service:
    build:
      context: ./apps/energy-calculation-service
      dockerfile: Dockerfile
    container_name: bess-pro-energy-calculation-prod
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "8110:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - CACHE_TTL_HOURS=168
      - MAX_CACHE_SIZE_MB=1000
    volumes:
      - energy_calculation_cache:/app/cache_pvgis
    networks:
      - bess-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Mailpit for email testing in production
  mailpit:
    image: axllent/mailpit
    container_name: bess-pro-mailpit
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "1026:1025"  # SMTP port
      - "8026:8025"  # Web UI port
    networks:
      - bess-network

volumes:
  mongodb_prod_data:
  mongodb_config:
  redis_prod_data:
  energy_calculation_cache:
  uploads:
  logs:

networks:
  bess-network:
    name: bess-network
    driver: bridge
    external: true
